name: Unit Tests

on:
    push:
        branches:
            - latest
            - next

    pull_request:
        branches:
            - latest
            - next

jobs:
    unit_tests:
        name: Unit tests

        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: List all files
              run: ls -alh

            - name: Check if Docker Compose is installed
              run: which docker-compose

            - name: Run Jest for unit tests
              run: sudo docker-compose run --rm yarn test
