name: Unit Tests

on:
    push:
        branches:
            - latest
            - next

    pull_request:
        branches:
            - latest
            - next

jobs:
    unit_tests:
        name: Unit tests

        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Installing the Node.js dependencies
              run: docker-compose run --user root --rm yarn

            - name: Run Jest for unit tests
              run: docker-compose run --user root --rm yarn test

            - name: Create the Coveralls configuration
              run: echo "repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}" > .coveralls.yml

            - name: Update the coverage
              run: docker-compose run --user root --rm yarn coverage
