name: Unit Tests

on:
    push:
        branches:
            - latest
            - next

    pull_request:
        branches:
            - latest
            - next

defaults:
    run:
        shell: bash
        working-directory: $GITHUB_WORKSPACE

jobs:
    unit_tests:
        name: Unit tests

        runs-on: ubuntu-latest

        steps:
            - name: Unit tests
              run: sudo docker-compose run --rm yarn test
